apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: treetracker-webapp-mvp
type: Opaque
stringData:
  keycloak-client-id: "treetracker-auth"
  keycloak-client-secret: "your-client-secret-change-in-production"
  keycloak-admin-username: "admin"
  keycloak-admin-password: "admin"
  fabric-admin-password: "adminpw"
  jwt-secret: "your-super-secret-jwt-key-change-in-production-please-use-256-bit-random-string"
  session-secret: "your-session-secret-change-in-production-please-use-random-string"
  admin-registration-secret: "change-me-admin-secret"
