apiVersion: v1
kind: Service
metadata:
  name: treetracker-auth-service-nodeport
  namespace: treetracker-webapp-mvp
  labels:
    app: treetracker-auth-service
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
    protocol: TCP
    name: http
  selector:
    app: treetracker-auth-service